### ISSUE TITLE
added api call to dictionary. can you review my code?

### ISSUE THREAD

**Issue by daymos** [FAC8-TheGoodParts/sexy-autocomplete#2]

**Comment by gabrielperales** [comment]
Ok, I wil do it ASAP :)

**Comment by daymos** [comment]
any reason why you prefer the callback?

**Comment by gabrielperales** [comment]
It was needed.  You can't return the content, you need to pass it through a function as a parameter.

**Comment by daymos** [comment]
oh, right right, I was just logging it

**Comment by gabrielperales** [comment]
In that case, have a callback will let you be more generic, and allow other behaviors
