### ISSUE TITLE
Unify code style

### ISSUE THREAD

**Issue by gabrielperales** [FAC8-TheGoodParts/sexy-autocomplete#6]
semicolons or not semicolons?? but no mix both styles!

Also we have to add an `editorconfig` file to use the same indentation.

**Comment by daymos** [comment]
ok we can go for semicolons.

**Comment by matthewiiv** [comment]
Are we going to combine the two projects?

**Comment by gabrielperales** [comment]
@matthewiiv those topics should be talked on gitter!
